// Tauri commands wrapping the claude-sync sidecar.
// All commands run the sidecar via run_sidecar, then parse stdout into typed structs.

use std::path::{Path, PathBuf};

use tauri::AppHandle;
use tauri_plugin_opener::OpenerExt;
use tauri_plugin_shell::ShellExt;

use crate::github;
use crate::parse;

// Default `.stowignore` body written by `create_default_stowignore`.
// Mirrors the conservative ignore set the sidecar's secret-scan recommends
// so first-run init doesn't get blocked by transient/cache files. Keep the
// list narrow — anything here is *never* synced, so over-including would
// silently drop user data.
const DEFAULT_STOWIGNORE: &str = "# claude-sync .stowignore \u{2014} generated by claude-sync-ui\n# Files and directories NOT pushed to the remote repository.\n\n# Tokens and credentials (NEVER sync)\n.credentials.json\n\n# Per-machine working state (often contains secrets)\nhistory.jsonl\nfile-history/\nshell-snapshots/\nprojects/\ntodos/\nsessions/\nsession-env/\n\n# Caches\ncache/\nimage-cache/\npaste-cache/\nbackups/\nide/\n\n# Daemon runtime\ndaemon/\ndaemon.lock\ndaemon.log\ndaemon.status.json\n\n# Cleanup markers\n.last-cleanup\n.serena/\nmcp-needs-auth-cache.json\n\n# Debug / job runtime\ndebug/\njobs/\n\n# Marketplace plugins with example credentials\nplugins/marketplaces/thedotmack/cursor-hooks/STANDALONE-SETUP.md\n";

#[derive(serde::Serialize, Clone)]
pub struct StatusResult {
    pub branch: String,
    pub ahead: u32,
    pub behind: u32,
    pub tracked: u32,
    pub changes: Vec<ChangeEntry>,
    pub excluded_stow: u32,
    pub excluded_git: u32,
}

#[derive(serde::Serialize, Clone)]
pub struct ChangeEntry {
    pub path: String,
    pub kind: String,
}

#[derive(serde::Serialize, Clone)]
pub struct PushResult {
    pub pushed: u32,
    pub commit_sha: Option<String>,
    pub message: Option<String>,
    pub nothing_to_push: bool,
}

#[derive(serde::Serialize, Clone)]
pub struct PullResult {
    pub kind: String,
    pub files: u32,
    pub commit_sha: Option<String>,
    pub conflict_files: u32,
}

#[derive(serde::Serialize, Clone)]
pub struct DoctorResult {
    pub overall: String,
    pub checks: Vec<DoctorCheck>,
}

#[derive(serde::Serialize, Clone)]
pub struct DoctorCheck {
    pub level: String,
    pub name: String,
    pub detail: String,
}

// Spawn the sidecar and collect full stdout/stderr/exit. Err only on spawn failure;
// callers decide how to handle non-zero exit codes (doctor wants the body either way).
async fn run_sidecar(app: &AppHandle, args: &[&str]) -> Result<(String, String, i32), String> {
    let output = app
        .shell()
        .sidecar("claude-sync")
        .map_err(|e| e.to_string())?
        .args(args)
        .output()
        .await
        .map_err(|e| e.to_string())?;

    let stdout = String::from_utf8_lossy(&output.stdout).to_string();
    let stderr = String::from_utf8_lossy(&output.stderr).to_string();
    let code = output.status.code().unwrap_or(-1);
    Ok((stdout, stderr, code))
}

fn fail_message(stderr: &str, stdout: &str) -> String {
    let s = stderr.trim();
    if !s.is_empty() {
        return s.to_string();
    }
    let o = stdout.trim();
    if !o.is_empty() {
        return o.to_string();
    }
    "claude-sync exited with non-zero status".to_string()
}

// claude-sync 0.x prints "Not initialized. Run `claude-sync init <remote>` first."
// on stdout with exit code 0 for read-only commands (status, doctor, pull). The
// UI needs an Err for that case so App.tsx can route to InitScreen — otherwise
// parse_status produces an empty StatusResult and the user lands on a broken
// main screen with no way out. Match leniently on the stdout prefix.
fn is_not_initialized_stdout(stdout: &str) -> bool {
    stdout.trim_start().starts_with("Not initialized")
}

// Defense in depth: the capability validator already rejects control chars and
// >2048-char strings, but we also sanity-check the URL in Rust so a future
// capability widening can't accidentally let bad input through to git.
fn validate_remote_url(remote: &str) -> Result<(), String> {
    if remote.is_empty() {
        return Err("Remote URL is empty".to_string());
    }
    if remote.len() > 2048 {
        return Err("Remote URL is too long (max 2048 chars)".to_string());
    }
    if remote.chars().any(|c| c.is_control()) {
        return Err("Remote URL contains control characters".to_string());
    }
    Ok(())
}

#[tauri::command]
pub async fn init(app: AppHandle, remote: String) -> Result<String, String> {
    validate_remote_url(&remote)?;
    let (stdout, stderr, code) = run_sidecar(&app, &["init", remote.as_str()]).await?;
    if code != 0 {
        return Err(fail_message(&stderr, &stdout));
    }
    Ok(stdout.trim().to_string())
}

#[tauri::command]
pub async fn status(app: AppHandle) -> Result<StatusResult, String> {
    let (stdout, stderr, code) = run_sidecar(&app, &["status"]).await?;
    if code != 0 {
        return Err(fail_message(&stderr, &stdout));
    }
    // Sidecar prints "Not initialized..." on stdout with exit 0 — translate to Err
    // so App.tsx can route to InitScreen instead of rendering an empty StatusResult.
    if is_not_initialized_stdout(&stdout) {
        return Err(stdout.trim().to_string());
    }
    Ok(parse::parse_status(&stdout))
}

// v0.2.6 — post-push verification.
// After a non-"Nothing to push" sidecar push, status.ahead must be 0
// (the remote-tracking ref has caught up). If it didn't, the sidecar
// reported a ghost success — common bug in the upstream claude-sync where
// the push subcommand commits locally but never reaches origin.
// Pure helper so the Tauri command (AppHandle-bound) can be exercised
// via unit tests without spinning up the sidecar.
fn verify_push_status(ahead: u32) -> Result<(), String> {
    if ahead == 0 {
        Ok(())
    } else {
        Err(format!(
            "push_unverified: sidecar reported success but origin is still {} commit(s) behind",
            ahead
        ))
    }
}

#[tauri::command]
pub async fn push(app: AppHandle, message: Option<String>) -> Result<PushResult, String> {
    let mut args: Vec<&str> = vec!["push"];
    if let Some(ref m) = message {
        if !m.is_empty() {
            args.push("-m");
            args.push(m.as_str());
        }
    }
    let (stdout, stderr, code) = run_sidecar(&app, &args).await?;
    if code != 0 {
        return Err(fail_message(&stderr, &stdout));
    }
    // "Not initialized" comes back on stdout w/ non-zero exit in the spec, but be defensive.
    if is_not_initialized_stdout(&stdout) {
        return Err(stdout.trim().to_string());
    }
    let result = parse::parse_push(&stdout);

    // "Nothing to push" — sidecar never actually called git push, so the
    // remote-tracking ref was never expected to change. Skip verification.
    if result.nothing_to_push {
        return Ok(result);
    }

    // v0.2.6 — verify the sidecar's success claim by re-reading status. The
    // sidecar's push command has been observed to print "Pushed N file(s) ->
    // origin/main" and exit 0 while the remote actually stayed empty. If
    // ahead > 0 after a non-empty push, surface a dedicated push_unverified
    // error so the UI can warn the user that data did not reach GitHub.
    //
    // IMPORTANT — verification accuracy depends on the sidecar's status
    // implementation: `parse_status::ahead` derives from
    // `git rev-list --count origin/<branch>..HEAD` style logic, which requires
    // the local remote-tracking ref (refs/remotes/origin/<branch>) to be
    // correctly updated by the sidecar's push step. If the sidecar's push is
    // the buggy one that omits the git-push stage entirely, this premise holds
    // (ahead stays > 0 → we catch it). But a future bug variant where the
    // sidecar updates the remote-tracking ref locally without pushing to
    // origin would silently pass this verification. Long-term mitigation
    // when the sidecar's push is rewritten: switch verification to
    // `git ls-remote origin <branch>` direct query.
    //
    // Defensive handling for two failure modes of the status check itself:
    //   - sidecar status returns an error    → wrap as push_unverified
    //   - sidecar prints "Not initialized." → tolerate (this would only
    //     happen if the repo was de-initialised between push and status,
    //     which the user would already see via the InitScreen on next render)
    //
    // TODO(v0.3) — wrap run_sidecar in tokio::time::timeout. The push command
    // now makes two sequential sidecar calls; if either hangs, the entire
    // Tauri command blocks indefinitely with no user feedback.
    let status_result = match run_sidecar(&app, &["status"]).await {
        Ok((st_out, st_err, st_code)) => {
            if st_code != 0 {
                return Err(format!(
                    "push_unverified: status check failed after push ({})",
                    fail_message(&st_err, &st_out)
                ));
            }
            // NOTE — this fallback is a known escape hatch: if the sidecar's status
            // responds with "Not initialized." after a successful push (extremely
            // rare, would require the repo being de-initialised between push and
            // status), we cannot verify ghost-push and return Ok(result). The user
            // will see the InitScreen on the next status refresh and re-configure.
            // A more conservative implementation would return push_unverified here,
            // but that would surface false alarms in the legitimate de-init case.
            if is_not_initialized_stdout(&st_out) {
                // Treat as benign — the InitScreen route will reappear on
                // next refresh and the user will reconfigure. Don't block
                // the push report.
                return Ok(result);
            }
            parse::parse_status(&st_out)
        }
        Err(e) => {
            return Err(format!(
                "push_unverified: status check failed after push ({})",
                e
            ));
        }
    };

    verify_push_status(status_result.ahead)?;
    Ok(result)
}

#[tauri::command]
pub async fn pull(app: AppHandle) -> Result<PullResult, String> {
    let (stdout, stderr, code) = run_sidecar(&app, &["pull"]).await?;
    // Conflict case may exit non-zero but still produces a parseable body — treat as success.
    if code != 0 && !stdout.contains("Merged with conflicts") {
        return Err(fail_message(&stderr, &stdout));
    }
    // Same "exit 0 + Not initialized on stdout" trap as status — surface to UI.
    if is_not_initialized_stdout(&stdout) {
        return Err(stdout.trim().to_string());
    }
    Ok(parse::parse_pull(&stdout))
}

#[tauri::command]
pub async fn doctor(app: AppHandle) -> Result<DoctorResult, String> {
    // Doctor returns exit 1 when overall FAIL; we still want the structured body for the UI.
    let (stdout, _stderr, _code) = run_sidecar(&app, &["doctor"]).await?;
    Ok(parse::parse_doctor(&stdout))
}

// Resolve `~/.claude/` using the same env-var precedence as the sidecar's
// `commands::util::home_dir`: HOME first, then USERPROFILE. Honors env overrides
// so tests can redirect the lookup without touching the real user profile.
fn resolve_claude_dir() -> Result<PathBuf, String> {
    let home = std::env::var_os("HOME")
        .or_else(|| std::env::var_os("USERPROFILE"))
        .map(PathBuf::from)
        .filter(|p| !p.as_os_str().is_empty())
        .ok_or_else(|| "could not determine home directory".to_string())?;
    Ok(home.join(".claude"))
}

// Rewrite the `url = ...` line inside `[remote "origin"]` of a git config text.
// We only mutate the first url inside the first origin section — anything else
// is left untouched so we don't accidentally clobber comments, push URLs, or
// other remotes. Returns Err if no origin section or no url line is present.
fn rewrite_origin_url(config: &str, new_url: &str) -> Result<String, String> {
    let mut out = String::new();
    let mut in_origin = false;
    let mut url_replaced = false;
    let mut found_origin = false;
    let trailing_newline = config.ends_with('\n');
    for line in config.lines() {
        let trimmed = line.trim_start();
        if trimmed.starts_with('[') {
            // Section header — switch context, preserve original line verbatim.
            in_origin = trimmed.trim_end() == "[remote \"origin\"]";
            if in_origin {
                found_origin = true;
            }
            out.push_str(line);
            out.push('\n');
            continue;
        }
        if in_origin && !url_replaced {
            // Match `url = ...` / `url=...` (git is case-sensitive on keys).
            let after_ws = line.trim_start();
            if let Some(rest) = after_ws.strip_prefix("url") {
                let rest = rest.trim_start();
                if rest.starts_with('=') {
                    let leading_ws: String =
                        line.chars().take_while(|c| c.is_whitespace()).collect();
                    out.push_str(&leading_ws);
                    out.push_str("url = ");
                    out.push_str(new_url);
                    out.push('\n');
                    url_replaced = true;
                    continue;
                }
            }
        }
        out.push_str(line);
        out.push('\n');
    }
    if !found_origin {
        return Err("origin remote not found in git config".to_string());
    }
    if !url_replaced {
        return Err("origin url not found in git config".to_string());
    }
    // Preserve the original file's trailing-newline state — `lines()` strips it.
    if !trailing_newline && out.ends_with('\n') {
        out.pop();
    }
    Ok(out)
}

// Atomically replace the `[remote "origin"]` URL in `~/.claude/.git/config`.
// Pure Rust (no shell out, no git2 dep) — we just read-modify-write the INI file.
// Writes via a sibling tempfile + rename so a crash mid-write can't corrupt the
// user's git config.
#[tauri::command]
pub async fn set_remote(new_url: String) -> Result<(), String> {
    validate_remote_url(&new_url)?;
    let claude_dir = resolve_claude_dir()?;
    let config_path = claude_dir.join(".git").join("config");
    if !config_path.exists() {
        return Err(
            "Not initialized. Run `claude-sync init <remote>` first.".to_string(),
        );
    }
    let original = std::fs::read_to_string(&config_path)
        .map_err(|e| format!("read {}: {e}", config_path.display()))?;
    let updated = rewrite_origin_url(&original, &new_url)?;
    if updated == original {
        // No-op: nothing to write, no risk to take.
        return Ok(());
    }
    // Per-call unique tempfile name so two concurrent set_remote invocations
    // (rare, but possible if the user double-clicks the Update button while
    // the modal hasn't disabled yet) don't trample each other's write. PID +
    // nanos is enough entropy for the realistic concurrency we expect here
    // without pulling in the `tempfile` crate.
    let nanos = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.subsec_nanos())
        .unwrap_or(0);
    let tmp_name = format!("config.tmp.{}.{}", std::process::id(), nanos);
    let tmp_path = config_path.with_file_name(tmp_name);
    std::fs::write(&tmp_path, &updated)
        .map_err(|e| format!("write {}: {e}", tmp_path.display()))?;
    std::fs::rename(&tmp_path, &config_path).map_err(|e| {
        // Best-effort cleanup so we don't leave a stray config.tmp.* behind.
        let _ = std::fs::remove_file(&tmp_path);
        format!("replace {}: {e}", config_path.display())
    })?;
    Ok(())
}

// Write a `.stowignore` file inside `claude_dir` containing the recommended
// default body. Atomic write (sibling tempfile + rename) so a crash mid-write
// can't leave a half-written `.stowignore` that the sidecar would then load.
//
// Contract:
//   - Err("claude_dir_not_found")  if claude_dir itself does not exist.
//     We deliberately do NOT mkdir it — claude-sync requires the user to
//     have a real `~/.claude/` from claude code; creating an empty one would
//     mask a much weirder bug.
//   - Err("stowignore_exists")     if `.stowignore` already exists. We never
//     overwrite — the user may have hand-edited it (e.g. the v0.2.2 hotfix
//     dogfood path) and clobbering would be hostile.
//   - Ok(())                       on a successful first-time write.
//
// Extracted out of `create_default_stowignore` so unit tests can target a
// temp directory without monkey-patching HOME/USERPROFILE (env-var mutation
// in parallel tests is racy + unsafe in 2024-edition Rust).
fn create_default_stowignore_at(claude_dir: &Path) -> Result<(), String> {
    if !claude_dir.exists() {
        return Err("claude_dir_not_found".to_string());
    }
    let target = claude_dir.join(".stowignore");
    if target.exists() {
        return Err("stowignore_exists".to_string());
    }
    // Same tempfile-naming scheme as set_remote — PID + nanos is enough
    // entropy for the realistic concurrency we expect (the button is
    // debounced in the UI but defense-in-depth is cheap).
    let nanos = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.subsec_nanos())
        .unwrap_or(0);
    let tmp_name = format!(".stowignore.tmp.{}.{}", std::process::id(), nanos);
    let tmp_path = claude_dir.join(tmp_name);
    std::fs::write(&tmp_path, DEFAULT_STOWIGNORE)
        .map_err(|e| format!("write {}: {e}", tmp_path.display()))?;
    std::fs::rename(&tmp_path, &target).map_err(|e| {
        // Best-effort cleanup so we don't leave a stray .stowignore.tmp.* behind.
        let _ = std::fs::remove_file(&tmp_path);
        format!("replace {}: {e}", target.display())
    })?;
    Ok(())
}

// Public command — resolves ~/.claude/ then delegates to the helper above.
// Surfaced to the FE so the ErrorBanner secret-scan action button can call
// this directly when the sidecar's init refuses on secret findings.
#[tauri::command]
pub async fn create_default_stowignore() -> Result<(), String> {
    let claude_dir = resolve_claude_dir()?;
    create_default_stowignore_at(&claude_dir)
}

// Return the contents of ~/.claude/.stowignore so the UI can show the user
// exactly which paths are excluded from sync. v0.2.4 dogfood report: a new
// user had no way to verify their per-machine directories (projects/,
// file-history/, ...) were actually being skipped — the only signal was the
// "excluded: stow N" count, which is opaque.
//
// Contract:
//   - Ok("")                     when ~/.claude/.stowignore does not exist
//                                (treated as "no exclusions" rather than an error)
//   - Ok(<file body>)            normal case
//   - Err(<read error>)          unreadable file (permissions, etc.)
//
// We intentionally read the file every call rather than caching — the user
// may hand-edit `.stowignore` between modal opens and the modal must reflect
// the current state.
#[tauri::command]
pub async fn read_stowignore() -> Result<String, String> {
    let claude_dir = resolve_claude_dir()?;
    let path = claude_dir.join(".stowignore");
    if !path.exists() {
        return Ok(String::new());
    }
    std::fs::read_to_string(&path).map_err(|e| format!("read {}: {e}", path.display()))
}

// ---- GitHub OAuth Device Flow (Phase B v0.2) -------------------------------
// These commands are stateless: the polling loop lives in the TS layer so we
// don't have to manage a long-running tokio task tied to a window's lifetime.

#[tauri::command]
pub async fn github_device_start() -> Result<github::DeviceCodeResponse, String> {
    github::start_device_flow().await
}

#[tauri::command]
pub async fn github_device_poll(
    device_code: String,
    current_interval: u64,
) -> Result<github::DevicePollResponse, String> {
    github::poll_device_flow(&device_code, current_interval).await
}

#[tauri::command]
pub fn github_is_logged_in() -> Result<bool, String> {
    Ok(github::has_token())
}

#[tauri::command]
pub fn github_logout() -> Result<(), String> {
    github::delete_token()
}

// Create a private GitHub repo on the authenticated user's account so the
// FE can immediately pipe the returned `clone_url` into `claude-sync init`.
// The actual error-string contract (not_logged_in / token_expired /
// forbidden / repo_taken / github_api_error:*) lives in github::create_repo.
#[tauri::command]
pub async fn github_create_repo(
    name: String,
    description: Option<String>,
) -> Result<github::RepoCreateResponse, String> {
    github::create_repo(&name, description.as_deref()).await
}

// Pure validator for the `open_in_editor` command. Extracted so unit tests
// can exercise the 5-stage path-traversal defence without needing an
// AppHandle. Returns the absolute canonical path on success. Stable error
// strings the FE pattern-matches: "absolute_path_rejected",
// "unc_path_rejected", "path_traversal_rejected", "file_not_found",
// "path_escapes_claude_dir", "resolve_claude_dir_failed: {e}".
fn validate_open_path(rel_path: &str, claude_dir: &Path) -> Result<PathBuf, String> {
    use std::path::Component;

    // Reject empty string and "." — claude_dir.join("") and join(".") both
    // resolve to claude_dir itself, which would open the directory in a file
    // manager instead of a file. Explicit reject is clearer than relying on
    // the canonicalize+starts_with combo to catch this.
    if rel_path.is_empty() || rel_path == "." {
        return Err("empty_path_rejected".to_string());
    }

    // Control chars (NUL byte etc.) cause platform-dependent EINVAL on open;
    // reject explicitly with a clear message instead of leaking through to
    // canonicalize() and surfacing as "file_not_found".
    if rel_path.chars().any(|c| c.is_control()) {
        return Err("path_contains_control_chars".to_string());
    }

    let p = Path::new(rel_path);

    // 1) UNC paths first (Windows "\\\\server\\share", POSIX "//host"). On
    //    Windows UNC also trips Path::is_absolute(), so we MUST check this
    //    before the absolute-path branch — otherwise UNC inputs report
    //    "absolute_path_rejected" instead of the more precise "unc_path_rejected".
    if rel_path.starts_with("\\\\") || rel_path.starts_with("//") {
        return Err("unc_path_rejected".to_string());
    }

    // 2) Absolute paths are rejected outright. We OR three checks because
    //    Path::is_absolute()'s semantics differ per host OS:
    //      - On Windows it returns false for "/etc/passwd" (no drive letter).
    //      - On POSIX it returns false for "C:\\Windows\\..." (no leading /).
    //    Adding explicit leading "/" and "\\" checks closes both gaps so the
    //    defence holds regardless of which OS the binary was built for.
    if p.is_absolute() || rel_path.starts_with('/') || rel_path.starts_with('\\') {
        return Err("absolute_path_rejected".to_string());
    }

    // 3a) Reject inline "." segments via raw-string match (e.g.
    //     "agents/./foo.md"). Path::components() normalises a mid-path "."
    //     away, so by the time we iterate components below it would be
    //     invisible — we have to catch it on the raw input first. Doesn't
    //     open anything dangerous on its own, but signals a malformed input
    //     we'd rather catch loudly with a clear error.
    if rel_path.contains("/./")
        || rel_path.contains("\\.\\")
        || rel_path.contains("/.\\")
        || rel_path.contains("\\./")
        || rel_path.starts_with("./")
        || rel_path.starts_with(".\\")
        || rel_path.ends_with("/.")
        || rel_path.ends_with("\\.")
    {
        return Err("path_traversal_rejected".to_string());
    }

    // 3b) Walk the components once: reject ParentDir (traversal), and reject
    //     Windows reserved device names ("NUL", "CON", "COM1"..."COM9",
    //     "LPT1"..."LPT9", "AUX", "PRN"). canonicalize() would resolve those
    //     device names to "\\.\NUL" etc. which falls outside claude_dir and
    //     gets caught by starts_with below, but that's incidental — we'd
    //     rather reject them with a clear message. Case-insensitive per
    //     Windows rules. Windows also treats "NUL.txt" the same way, so we
    //     strip the extension before comparing.
    const RESERVED: &[&str] = &[
        "NUL", "CON", "AUX", "PRN",
        "COM1", "COM2", "COM3", "COM4", "COM5", "COM6", "COM7", "COM8", "COM9",
        "LPT1", "LPT2", "LPT3", "LPT4", "LPT5", "LPT6", "LPT7", "LPT8", "LPT9",
    ];
    for component in p.components() {
        match component {
            Component::ParentDir => {
                return Err("path_traversal_rejected".to_string());
            }
            Component::Normal(os) => {
                if let Some(s) = os.to_str() {
                    // Strip an extension (Windows treats "NUL.txt" the same way).
                    let stem = s.split('.').next().unwrap_or(s);
                    if RESERVED.iter().any(|r| r.eq_ignore_ascii_case(stem)) {
                        return Err("reserved_device_name".to_string());
                    }
                }
            }
            _ => {}
        }
    }

    // 4) Join under claude_dir.
    let candidate = claude_dir.join(rel_path);

    // 5) canonicalize() resolves symlinks AND requires the file to exist.
    //    Missing file → "file_not_found". Symlinks pointing outside
    //    claude_dir → caught by the starts_with check below.
    let canonical = candidate
        .canonicalize()
        .map_err(|_| "file_not_found".to_string())?;

    // 6) Canonicalise claude_dir too so the comparison is apples-to-apples
    //    (Windows \\?\ extended-length prefixes match either both or neither).
    let canonical_claude = claude_dir
        .canonicalize()
        .map_err(|e| format!("resolve_claude_dir_failed: {e}"))?;

    if !canonical.starts_with(&canonical_claude) {
        return Err("path_escapes_claude_dir".to_string());
    }

    Ok(canonical)
}

// v0.2.5 — double-click a tracked file in the FileTree to open it with
// the OS's default editor (Notepad/VSCode/... on Windows, TextEdit/...
// on macOS, xdg-open on Linux). The frontend hands us a path relative to
// ~/.claude/; we validate (5-stage defence in `validate_open_path`),
// canonicalise, and hand the absolute path to the opener plugin's Rust
// API. Going through Rust keeps path-traversal defence inside the trust
// boundary and bypasses the capability ACL on `opener:open_path` that we
// otherwise would have to widen.
#[tauri::command]
pub async fn open_in_editor(app: AppHandle, rel_path: String) -> Result<(), String> {
    let claude_dir = resolve_claude_dir()?;
    let canonical = validate_open_path(&rel_path, &claude_dir)?;
    let canonical_str = canonical
        .to_str()
        .ok_or_else(|| "path_not_utf8".to_string())?;
    app.opener()
        .open_path(canonical_str, None::<&str>)
        .map_err(|e| format!("opener_failed: {e}"))
}

#[cfg(test)]
mod tests {
    use super::{
        create_default_stowignore_at, fail_message, is_not_initialized_stdout,
        rewrite_origin_url, validate_open_path, validate_remote_url, verify_push_status,
        DEFAULT_STOWIGNORE,
    };
    use std::path::PathBuf;

    // Small per-test temp dir without pulling in the `tempfile` crate. PID +
    // nanos + thread-id keeps it unique across parallel cargo-test threads.
    fn make_tempdir(tag: &str) -> PathBuf {
        let nanos = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .map(|d| d.as_nanos())
            .unwrap_or(0);
        let thread = std::thread::current();
        // Replace any path-unfriendly chars in thread name with '_'.
        let safe_thread: String = thread
            .name()
            .unwrap_or("unnamed")
            .chars()
            .map(|c| if c.is_ascii_alphanumeric() { c } else { '_' })
            .collect();
        let dir = std::env::temp_dir().join(format!(
            "csui-test-{}-{}-{}-{}",
            tag,
            std::process::id(),
            safe_thread,
            nanos
        ));
        std::fs::create_dir_all(&dir).expect("make_tempdir: create_dir_all");
        dir
    }

    #[test]
    fn rejects_empty_url() {
        assert!(validate_remote_url("").is_err());
    }

    #[test]
    fn rejects_control_chars() {
        assert!(validate_remote_url("git@github.com:me/dot\nclaude.git").is_err());
        assert!(validate_remote_url("git@github.com:me/dot\x00claude.git").is_err());
        assert!(validate_remote_url("git@github.com:me/dot\x1bclaude.git").is_err());
    }

    #[test]
    fn rejects_oversized_url() {
        let url = "a".repeat(2049);
        assert!(validate_remote_url(&url).is_err());
    }

    #[test]
    fn accepts_typical_urls() {
        assert!(validate_remote_url("git@github.com:me/dotclaude.git").is_ok());
        assert!(validate_remote_url("https://github.com/me/dotclaude.git").is_ok());
        assert!(validate_remote_url("ssh://git@example.com/repo.git").is_ok());
    }

    #[test]
    fn accepts_max_length_url() {
        let url = "a".repeat(2048);
        assert!(validate_remote_url(&url).is_ok());
    }

    // Regression: claude-sync 0.x prints "Not initialized..." on stdout with
    // exit code 0 for read-only commands. The helper must flag that string so
    // status() returns Err and the UI shows InitScreen.
    #[test]
    fn detects_not_initialized_stdout() {
        assert!(is_not_initialized_stdout(
            "Not initialized. Run `claude-sync init <remote>` first.\n"
        ));
        // Tolerate leading whitespace — the sidecar might add a newline first.
        assert!(is_not_initialized_stdout(
            "\n  Not initialized. Run `claude-sync init <remote>` first."
        ));
    }

    #[test]
    fn ignores_unrelated_stdout() {
        assert!(!is_not_initialized_stdout(""));
        assert!(!is_not_initialized_stdout(
            "Branch: main (ahead 0, behind 0)\nNothing changed\n"
        ));
        assert!(!is_not_initialized_stdout(
            "Pushed 3 file(s) -> origin/main\n"
        ));
        // "not initialized" lowercase elsewhere in the line must not trigger it.
        assert!(!is_not_initialized_stdout(
            "Branch: main\n  some submodule is not initialized yet\n"
        ));
    }

    #[test]
    fn fail_message_prefers_stderr_then_stdout_then_default() {
        assert_eq!(fail_message("boom", "ignored"), "boom");
        assert_eq!(fail_message("", "stdout body"), "stdout body");
        assert_eq!(
            fail_message("", ""),
            "claude-sync exited with non-zero status"
        );
    }

    // Typical config produced by `git2::Repository::remote("origin", ...)` —
    // tab indented, `url = ...` on its own line. Make sure the rewrite hits
    // only that line and leaves everything else alone.
    #[test]
    fn rewrite_replaces_origin_url() {
        let input = "[core]\n\trepositoryformatversion = 0\n[remote \"origin\"]\n\turl = git@old.example.com:me/dot.git\n\tfetch = +refs/heads/*:refs/remotes/origin/*\n";
        let out = rewrite_origin_url(input, "git@new.example.com:me/dot.git").unwrap();
        assert!(out.contains("url = git@new.example.com:me/dot.git"));
        assert!(!out.contains("git@old.example.com"));
        // The fetch line and other sections must survive unchanged.
        assert!(out.contains("fetch = +refs/heads/*:refs/remotes/origin/*"));
        assert!(out.contains("[core]"));
        assert!(out.contains("repositoryformatversion = 0"));
    }

    // Other remotes (e.g. an `upstream` mirror) and any non-url keys in the
    // origin section must be preserved untouched.
    #[test]
    fn rewrite_only_touches_origin_section() {
        let input = "[remote \"origin\"]\n\turl = https://old/a.git\n[remote \"upstream\"]\n\turl = https://other/b.git\n";
        let out = rewrite_origin_url(input, "https://new/a.git").unwrap();
        assert!(out.contains("url = https://new/a.git"));
        assert!(out.contains("url = https://other/b.git"));
    }

    #[test]
    fn rewrite_fails_without_origin_section() {
        let input = "[core]\n\trepositoryformatversion = 0\n";
        assert!(rewrite_origin_url(input, "git@new/repo.git").is_err());
    }

    #[test]
    fn rewrite_fails_with_origin_but_no_url() {
        let input = "[remote \"origin\"]\n\tfetch = +refs/heads/*:refs/remotes/origin/*\n";
        assert!(rewrite_origin_url(input, "git@new/repo.git").is_err());
    }

    #[test]
    fn rewrite_preserves_trailing_newline_state() {
        let with_nl = "[remote \"origin\"]\n\turl = a\n";
        let no_nl = "[remote \"origin\"]\n\turl = a";
        assert!(rewrite_origin_url(with_nl, "b").unwrap().ends_with('\n'));
        assert!(!rewrite_origin_url(no_nl, "b").unwrap().ends_with('\n'));
    }

    // v0.2.3 hotfix: secret-scan dogfood path — the FE calls
    // create_default_stowignore() when claude-sync's secret-scan blocks init.
    // First-time write must succeed and produce exactly the canonical body.
    #[test]
    fn create_stowignore_writes_default_body_when_missing() {
        let dir = make_tempdir("stowignore-write");
        let result = create_default_stowignore_at(&dir);
        assert!(result.is_ok(), "expected Ok, got {:?}", result);
        let body = std::fs::read_to_string(dir.join(".stowignore"))
            .expect("read_to_string after write");
        assert_eq!(body, DEFAULT_STOWIGNORE);
        // The body must include the load-bearing entries the dogfood bug
        // surfaced — if any one of these regresses, a fresh init re-traps.
        assert!(body.contains(".credentials.json"));
        assert!(body.contains("file-history/"));
        assert!(body.contains("projects/"));
        let _ = std::fs::remove_dir_all(&dir);
    }

    // The user may have hand-written their own .stowignore (exactly what
    // unblocked the v0.2.2 user). We must never clobber that file — Err out
    // with a stable string the FE pattern-matches to show "edit manually".
    #[test]
    fn create_stowignore_refuses_when_already_present() {
        let dir = make_tempdir("stowignore-exists");
        std::fs::write(dir.join(".stowignore"), "# user-managed\n.credentials.json\n")
            .expect("seed existing .stowignore");
        let err = create_default_stowignore_at(&dir).unwrap_err();
        assert_eq!(err, "stowignore_exists");
        // Confirm the user's hand-written body survived untouched.
        let body = std::fs::read_to_string(dir.join(".stowignore")).unwrap();
        assert!(body.starts_with("# user-managed"));
        let _ = std::fs::remove_dir_all(&dir);
    }

    // resolve_claude_dir would normally hand back a valid path, but if it
    // points somewhere that doesn't exist (e.g. corrupted HOME env, or a
    // first-run system that never had `~/.claude/` populated) we surface a
    // stable error instead of silently mkdir'ing — creating an empty
    // ~/.claude/ would mask a much weirder bug.
    #[test]
    fn create_stowignore_errors_when_claude_dir_missing() {
        let dir = make_tempdir("stowignore-missing")
            .join("definitely-does-not-exist-subdir");
        assert!(!dir.exists());
        let err = create_default_stowignore_at(&dir).unwrap_err();
        assert_eq!(err, "claude_dir_not_found");
    }

    // v0.2.5 — open_in_editor path-traversal defence. The FE hands us a path
    // relative to ~/.claude/; validate_open_path is the pure helper that
    // enforces the 5-stage check (no abs path / no UNC / no .. / must exist /
    // must stay under claude_dir). These tests cover each stage's stable
    // error string so the FE can keep pattern-matching them.
    #[test]
    fn open_in_editor_rejects_absolute_path_windows() {
        let dir = make_tempdir("oie-abs-win");
        assert_eq!(
            validate_open_path("C:\\Windows\\system32\\cmd.exe", &dir).unwrap_err(),
            "absolute_path_rejected"
        );
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn open_in_editor_rejects_absolute_path_unix() {
        let dir = make_tempdir("oie-abs-unix");
        assert_eq!(
            validate_open_path("/etc/passwd", &dir).unwrap_err(),
            "absolute_path_rejected"
        );
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn open_in_editor_rejects_unc() {
        let dir = make_tempdir("oie-unc");
        assert_eq!(
            validate_open_path("\\\\server\\share\\file", &dir).unwrap_err(),
            "unc_path_rejected"
        );
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn open_in_editor_rejects_dotdot_direct() {
        let dir = make_tempdir("oie-dd-direct");
        assert_eq!(
            validate_open_path("../outside.md", &dir).unwrap_err(),
            "path_traversal_rejected"
        );
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn open_in_editor_rejects_dotdot_nested() {
        let dir = make_tempdir("oie-dd-nested");
        assert_eq!(
            validate_open_path("agents/../../outside.md", &dir).unwrap_err(),
            "path_traversal_rejected"
        );
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn open_in_editor_rejects_nonexistent_file() {
        let dir = make_tempdir("oie-missing");
        assert_eq!(
            validate_open_path("definitely_not_a_real_file_xyz.md", &dir).unwrap_err(),
            "file_not_found"
        );
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn open_in_editor_accepts_existing_file_under_claude_dir() {
        let dir = make_tempdir("oie-ok");
        let file = dir.join("settings.json");
        std::fs::write(&file, "{}").expect("seed file");
        let result = validate_open_path("settings.json", &dir).expect("should accept");
        // canonicalize() may add \\?\ on Windows — compare via canonicalize.
        let expected = file.canonicalize().expect("canonicalize seed");
        assert_eq!(result, expected);
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn open_in_editor_rejects_empty_path() {
        let dir = make_tempdir("oie-empty");
        assert_eq!(
            validate_open_path("", &dir).unwrap_err(),
            "empty_path_rejected"
        );
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn open_in_editor_rejects_dot() {
        let dir = make_tempdir("oie-dot");
        assert_eq!(
            validate_open_path(".", &dir).unwrap_err(),
            "empty_path_rejected"
        );
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn open_in_editor_rejects_control_chars() {
        let dir = make_tempdir("oie-ctrl");
        assert_eq!(
            validate_open_path("a\x00b.md", &dir).unwrap_err(),
            "path_contains_control_chars"
        );
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn open_in_editor_rejects_windows_reserved_names() {
        let dir = make_tempdir("oie-reserved");
        // Plain name
        assert_eq!(
            validate_open_path("NUL", &dir).unwrap_err(),
            "reserved_device_name"
        );
        // Lowercase (Windows is case-insensitive)
        assert_eq!(
            validate_open_path("nul", &dir).unwrap_err(),
            "reserved_device_name"
        );
        // With extension
        assert_eq!(
            validate_open_path("CON.txt", &dir).unwrap_err(),
            "reserved_device_name"
        );
        // Inside subdirectory
        assert_eq!(
            validate_open_path("agents/COM1", &dir).unwrap_err(),
            "reserved_device_name"
        );
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn open_in_editor_rejects_curdir_component() {
        let dir = make_tempdir("oie-curdir");
        assert_eq!(
            validate_open_path("agents/./foo.md", &dir).unwrap_err(),
            "path_traversal_rejected"
        );
        let _ = std::fs::remove_dir_all(&dir);
    }

    // v0.2.6 — ghost-push detector. After a non-trivial push, status.ahead
    // must be 0 (remote-tracking ref caught up). If it didn't, the sidecar
    // lied; we surface a dedicated `push_unverified:`-prefixed error so the
    // FE can show a targeted warning instead of the generic action-failed
    // toast.
    #[test]
    fn verify_push_status_ok_when_ahead_zero() {
        assert!(verify_push_status(0).is_ok());
    }

    #[test]
    fn verify_push_status_err_when_ahead_nonzero() {
        let e = verify_push_status(3).unwrap_err();
        assert!(
            e.starts_with("push_unverified:"),
            "expected 'push_unverified:' prefix, got: {e}"
        );
        assert!(e.contains("3 commit(s) behind"));
    }
}
